# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zzg/cpp/object_memory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zzg/cpp/object_memory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zzg/cpp/object_memory/CMakeFiles /home/zzg/cpp/object_memory/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zzg/cpp/object_memory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testheap

# Build rule for target.
testheap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testheap
.PHONY : testheap

# fast build rule for target.
testheap/fast:
	$(MAKE) -f CMakeFiles/testheap.dir/build.make CMakeFiles/testheap.dir/build
.PHONY : testheap/fast

#=============================================================================
# Target rules for targets named object_memory

# Build rule for target.
object_memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 object_memory
.PHONY : object_memory

# fast build rule for target.
object_memory/fast:
	$(MAKE) -f CMakeFiles/object_memory.dir/build.make CMakeFiles/object_memory.dir/build
.PHONY : object_memory/fast

#=============================================================================
# Target rules for targets named testmalloc

# Build rule for target.
testmalloc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testmalloc
.PHONY : testmalloc

# fast build rule for target.
testmalloc/fast:
	$(MAKE) -f CMakeFiles/testmalloc.dir/build.make CMakeFiles/testmalloc.dir/build
.PHONY : testmalloc/fast

#=============================================================================
# Target rules for targets named testnew

# Build rule for target.
testnew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testnew
.PHONY : testnew

# fast build rule for target.
testnew/fast:
	$(MAKE) -f CMakeFiles/testnew.dir/build.make CMakeFiles/testnew.dir/build
.PHONY : testnew/fast

#=============================================================================
# Target rules for targets named testblock

# Build rule for target.
testblock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testblock
.PHONY : testblock

# fast build rule for target.
testblock/fast:
	$(MAKE) -f CMakeFiles/testblock.dir/build.make CMakeFiles/testblock.dir/build
.PHONY : testblock/fast

#=============================================================================
# Target rules for targets named teststack

# Build rule for target.
teststack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 teststack
.PHONY : teststack

# fast build rule for target.
teststack/fast:
	$(MAKE) -f CMakeFiles/teststack.dir/build.make CMakeFiles/teststack.dir/build
.PHONY : teststack/fast

#=============================================================================
# Target rules for targets named testarray

# Build rule for target.
testarray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testarray
.PHONY : testarray

# fast build rule for target.
testarray/fast:
	$(MAKE) -f CMakeFiles/testarray.dir/build.make CMakeFiles/testarray.dir/build
.PHONY : testarray/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/object_memory.dir/build.make CMakeFiles/object_memory.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/object_memory.dir/build.make CMakeFiles/object_memory.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/object_memory.dir/build.make CMakeFiles/object_memory.dir/main.cpp.s
.PHONY : main.cpp.s

test_array/main.o: test_array/main.cpp.o

.PHONY : test_array/main.o

# target to build an object file
test_array/main.cpp.o:
	$(MAKE) -f CMakeFiles/testarray.dir/build.make CMakeFiles/testarray.dir/test_array/main.cpp.o
.PHONY : test_array/main.cpp.o

test_array/main.i: test_array/main.cpp.i

.PHONY : test_array/main.i

# target to preprocess a source file
test_array/main.cpp.i:
	$(MAKE) -f CMakeFiles/testarray.dir/build.make CMakeFiles/testarray.dir/test_array/main.cpp.i
.PHONY : test_array/main.cpp.i

test_array/main.s: test_array/main.cpp.s

.PHONY : test_array/main.s

# target to generate assembly for a file
test_array/main.cpp.s:
	$(MAKE) -f CMakeFiles/testarray.dir/build.make CMakeFiles/testarray.dir/test_array/main.cpp.s
.PHONY : test_array/main.cpp.s

test_block/main.o: test_block/main.cpp.o

.PHONY : test_block/main.o

# target to build an object file
test_block/main.cpp.o:
	$(MAKE) -f CMakeFiles/testblock.dir/build.make CMakeFiles/testblock.dir/test_block/main.cpp.o
.PHONY : test_block/main.cpp.o

test_block/main.i: test_block/main.cpp.i

.PHONY : test_block/main.i

# target to preprocess a source file
test_block/main.cpp.i:
	$(MAKE) -f CMakeFiles/testblock.dir/build.make CMakeFiles/testblock.dir/test_block/main.cpp.i
.PHONY : test_block/main.cpp.i

test_block/main.s: test_block/main.cpp.s

.PHONY : test_block/main.s

# target to generate assembly for a file
test_block/main.cpp.s:
	$(MAKE) -f CMakeFiles/testblock.dir/build.make CMakeFiles/testblock.dir/test_block/main.cpp.s
.PHONY : test_block/main.cpp.s

test_heap/main.o: test_heap/main.cpp.o

.PHONY : test_heap/main.o

# target to build an object file
test_heap/main.cpp.o:
	$(MAKE) -f CMakeFiles/testheap.dir/build.make CMakeFiles/testheap.dir/test_heap/main.cpp.o
.PHONY : test_heap/main.cpp.o

test_heap/main.i: test_heap/main.cpp.i

.PHONY : test_heap/main.i

# target to preprocess a source file
test_heap/main.cpp.i:
	$(MAKE) -f CMakeFiles/testheap.dir/build.make CMakeFiles/testheap.dir/test_heap/main.cpp.i
.PHONY : test_heap/main.cpp.i

test_heap/main.s: test_heap/main.cpp.s

.PHONY : test_heap/main.s

# target to generate assembly for a file
test_heap/main.cpp.s:
	$(MAKE) -f CMakeFiles/testheap.dir/build.make CMakeFiles/testheap.dir/test_heap/main.cpp.s
.PHONY : test_heap/main.cpp.s

test_malloc/main.o: test_malloc/main.cpp.o

.PHONY : test_malloc/main.o

# target to build an object file
test_malloc/main.cpp.o:
	$(MAKE) -f CMakeFiles/testmalloc.dir/build.make CMakeFiles/testmalloc.dir/test_malloc/main.cpp.o
.PHONY : test_malloc/main.cpp.o

test_malloc/main.i: test_malloc/main.cpp.i

.PHONY : test_malloc/main.i

# target to preprocess a source file
test_malloc/main.cpp.i:
	$(MAKE) -f CMakeFiles/testmalloc.dir/build.make CMakeFiles/testmalloc.dir/test_malloc/main.cpp.i
.PHONY : test_malloc/main.cpp.i

test_malloc/main.s: test_malloc/main.cpp.s

.PHONY : test_malloc/main.s

# target to generate assembly for a file
test_malloc/main.cpp.s:
	$(MAKE) -f CMakeFiles/testmalloc.dir/build.make CMakeFiles/testmalloc.dir/test_malloc/main.cpp.s
.PHONY : test_malloc/main.cpp.s

test_new/main.o: test_new/main.cpp.o

.PHONY : test_new/main.o

# target to build an object file
test_new/main.cpp.o:
	$(MAKE) -f CMakeFiles/testnew.dir/build.make CMakeFiles/testnew.dir/test_new/main.cpp.o
.PHONY : test_new/main.cpp.o

test_new/main.i: test_new/main.cpp.i

.PHONY : test_new/main.i

# target to preprocess a source file
test_new/main.cpp.i:
	$(MAKE) -f CMakeFiles/testnew.dir/build.make CMakeFiles/testnew.dir/test_new/main.cpp.i
.PHONY : test_new/main.cpp.i

test_new/main.s: test_new/main.cpp.s

.PHONY : test_new/main.s

# target to generate assembly for a file
test_new/main.cpp.s:
	$(MAKE) -f CMakeFiles/testnew.dir/build.make CMakeFiles/testnew.dir/test_new/main.cpp.s
.PHONY : test_new/main.cpp.s

test_stack/main.o: test_stack/main.cpp.o

.PHONY : test_stack/main.o

# target to build an object file
test_stack/main.cpp.o:
	$(MAKE) -f CMakeFiles/teststack.dir/build.make CMakeFiles/teststack.dir/test_stack/main.cpp.o
.PHONY : test_stack/main.cpp.o

test_stack/main.i: test_stack/main.cpp.i

.PHONY : test_stack/main.i

# target to preprocess a source file
test_stack/main.cpp.i:
	$(MAKE) -f CMakeFiles/teststack.dir/build.make CMakeFiles/teststack.dir/test_stack/main.cpp.i
.PHONY : test_stack/main.cpp.i

test_stack/main.s: test_stack/main.cpp.s

.PHONY : test_stack/main.s

# target to generate assembly for a file
test_stack/main.cpp.s:
	$(MAKE) -f CMakeFiles/teststack.dir/build.make CMakeFiles/teststack.dir/test_stack/main.cpp.s
.PHONY : test_stack/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... testheap"
	@echo "... object_memory"
	@echo "... rebuild_cache"
	@echo "... testmalloc"
	@echo "... testnew"
	@echo "... testblock"
	@echo "... teststack"
	@echo "... testarray"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_array/main.o"
	@echo "... test_array/main.i"
	@echo "... test_array/main.s"
	@echo "... test_block/main.o"
	@echo "... test_block/main.i"
	@echo "... test_block/main.s"
	@echo "... test_heap/main.o"
	@echo "... test_heap/main.i"
	@echo "... test_heap/main.s"
	@echo "... test_malloc/main.o"
	@echo "... test_malloc/main.i"
	@echo "... test_malloc/main.s"
	@echo "... test_new/main.o"
	@echo "... test_new/main.i"
	@echo "... test_new/main.s"
	@echo "... test_stack/main.o"
	@echo "... test_stack/main.i"
	@echo "... test_stack/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

